name: Security · Secret Scan

on:
  workflow_dispatch:
    inputs:
      full-history:
        required: false
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  scan:
    uses: Bharathkumar045/github-tests/.github/workflows/secret-scanning.yml@main
    secrets: inherit
    with:
      full-history: ${{ inputs.full-history }}
